import dayjs from 'dayjs';

export interface IUSDAUpdateMst {
  id?: number;
  addedSugarsgperServing?: string | null;
  allAllergens?: string | null;
  brandName?: string | null;
  calciumCamgperServing?: number | null;
  calorieskcalperServing?: string | null;
  cholesterolmgperServing?: string | null;
  cNCredited?: string | null;
  cNCrediting?: string | null;
  cNExpirationDate?: string | null;
  cNLabelDocument?: string | null;
  cNLabelStatement?: string | null;
  cNProductIdentification?: string | null;
  cNQualified?: string | null;
  cNQualifierCode?: string | null;
  dietaryFibergperServing?: string | null;
  downloaded?: dayjs.Dayjs | null;
  eggs?: string | null;
  fish?: string | null;
  foodCategory?: string | null;
  functionalname?: string | null;
  gtin?: string | null;
  halal?: string | null;
  hierarchicalPlacement?: string | null;
  informationProvider?: string | null;
  ingredientsenglish?: string | null;
  ironFemgperServing?: string | null;
  kosher?: string | null;
  lastupdated?: dayjs.Dayjs | null;
  longdescription?: string | null;
  milk?: string | null;
  nutrientFormatTypeCodeReferenceCode?: string | null;
  nutrientQuantityBasisTypeCode?: string | null;
  nutrientQuantityBasisUnitofMeasure?: string | null;
  nutrientQuantityBasisValue?: string | null;
  nutrientsperservingcalculatedfrombymeasurereportedamount?: boolean | null;
  peanuts?: string | null;
  pFSCreditableIngredientTypeCode?: string | null;
  pFSDocument?: string | null;
  pFSTotalCreditableIngredientAmount?: string | null;
  pFSTotalPortionWeight?: string | null;
  potassiumKmgperServing?: string | null;
  preparationStateCode?: string | null;
  productFormulationStatement?: string | null;
  proteingperServing?: string | null;
  saturatedFatgperServing?: number | null;
  servingDescription?: string | null;
  servingSize?: string | null;
  servingUnitofMeasure?: string | null;
  servingsPerCase?: string | null;
  sesame?: string | null;
  shellfish?: string | null;
  shortdescription?: string | null;
  sodiummgperServing?: string | null;
  soybeans?: string | null;
  sugarsgperServing?: string | null;
  totalCarbohydrategperServing?: number | null;
  totalFatgperServing?: string | null;
  tradeChannels?: string | null;
  transFatgperServing?: string | null;
  treeNuts?: string | null;
  uSDAFoodsMaterialCode?: string | null;
  uSDAFoodsProductsDescription?: string | null;
  vendorName?: string | null;
  vendorID?: string | null;
  vitaminDmcgperServing?: string | null;
  wheat?: string | null;
}

export const defaultValue: Readonly<IUSDAUpdateMst> = {
  nutrientsperservingcalculatedfrombymeasurereportedamount: false,
};
