package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AllergenMstAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergenMstAllPropertiesEquals(AllergenMst expected, AllergenMst actual) {
        assertAllergenMstAutoGeneratedPropertiesEquals(expected, actual);
        assertAllergenMstAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergenMstAllUpdatablePropertiesEquals(AllergenMst expected, AllergenMst actual) {
        assertAllergenMstUpdatableFieldsEquals(expected, actual);
        assertAllergenMstUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergenMstAutoGeneratedPropertiesEquals(AllergenMst expected, AllergenMst actual) {
        assertThat(expected)
            .as("Verify AllergenMst auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergenMstUpdatableFieldsEquals(AllergenMst expected, AllergenMst actual) {
        assertThat(expected)
            .as("Verify AllergenMst relevant properties")
            .satisfies(e -> assertThat(e.getAllergenGroup()).as("check allergenGroup").isEqualTo(actual.getAllergenGroup()))
            .satisfies(e -> assertThat(e.getAllergenId()).as("check allergenId").isEqualTo(actual.getAllergenId()))
            .satisfies(e -> assertThat(e.getAllergenName()).as("check allergenName").isEqualTo(actual.getAllergenName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergenMstUpdatableRelationshipsEquals(AllergenMst expected, AllergenMst actual) {
        // empty method
    }
}
