package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DistributorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributorAllPropertiesEquals(Distributor expected, Distributor actual) {
        assertDistributorAutoGeneratedPropertiesEquals(expected, actual);
        assertDistributorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributorAllUpdatablePropertiesEquals(Distributor expected, Distributor actual) {
        assertDistributorUpdatableFieldsEquals(expected, actual);
        assertDistributorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributorAutoGeneratedPropertiesEquals(Distributor expected, Distributor actual) {
        assertThat(expected)
            .as("Verify Distributor auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributorUpdatableFieldsEquals(Distributor expected, Distributor actual) {
        assertThat(expected)
            .as("Verify Distributor relevant properties")
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedOn()).as("check createdOn").isEqualTo(actual.getCreatedOn()))
            .satisfies(e -> assertThat(e.getDistributorCode()).as("check distributorCode").isEqualTo(actual.getDistributorCode()))
            .satisfies(e -> assertThat(e.getDistributorID()).as("check distributorID").isEqualTo(actual.getDistributorID()))
            .satisfies(e -> assertThat(e.getDistributorName()).as("check distributorName").isEqualTo(actual.getDistributorName()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedOn()).as("check updatedOn").isEqualTo(actual.getUpdatedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistributorUpdatableRelationshipsEquals(Distributor expected, Distributor actual) {
        // empty method
    }
}
