package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class H7KeywordMstAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertH7KeywordMstAllPropertiesEquals(H7KeywordMst expected, H7KeywordMst actual) {
        assertH7KeywordMstAutoGeneratedPropertiesEquals(expected, actual);
        assertH7KeywordMstAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertH7KeywordMstAllUpdatablePropertiesEquals(H7KeywordMst expected, H7KeywordMst actual) {
        assertH7KeywordMstUpdatableFieldsEquals(expected, actual);
        assertH7KeywordMstUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertH7KeywordMstAutoGeneratedPropertiesEquals(H7KeywordMst expected, H7KeywordMst actual) {
        assertThat(expected)
            .as("Verify H7KeywordMst auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertH7KeywordMstUpdatableFieldsEquals(H7KeywordMst expected, H7KeywordMst actual) {
        assertThat(expected)
            .as("Verify H7KeywordMst relevant properties")
            .satisfies(e -> assertThat(e.geth7Group()).as("check h7Group").isEqualTo(actual.geth7Group()))
            .satisfies(e -> assertThat(e.geth7Keyword()).as("check h7Keyword").isEqualTo(actual.geth7Keyword()))
            .satisfies(e -> assertThat(e.geth7keywordId()).as("check h7keywordId").isEqualTo(actual.geth7keywordId()))
            .satisfies(e -> assertThat(e.getIocGroup()).as("check iocGroup").isEqualTo(actual.getIocGroup()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertH7KeywordMstUpdatableRelationshipsEquals(H7KeywordMst expected, H7KeywordMst actual) {
        // empty method
    }
}
