package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IocCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIocCategoryAllPropertiesEquals(IocCategory expected, IocCategory actual) {
        assertIocCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertIocCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIocCategoryAllUpdatablePropertiesEquals(IocCategory expected, IocCategory actual) {
        assertIocCategoryUpdatableFieldsEquals(expected, actual);
        assertIocCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIocCategoryAutoGeneratedPropertiesEquals(IocCategory expected, IocCategory actual) {
        assertThat(expected)
            .as("Verify IocCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIocCategoryUpdatableFieldsEquals(IocCategory expected, IocCategory actual) {
        assertThat(expected)
            .as("Verify IocCategory relevant properties")
            .satisfies(e -> assertThat(e.getIocCategoryColor()).as("check iocCategoryColor").isEqualTo(actual.getIocCategoryColor()))
            .satisfies(e -> assertThat(e.getIocCategoryId()).as("check iocCategoryId").isEqualTo(actual.getIocCategoryId()))
            .satisfies(e -> assertThat(e.getIocCategoryName()).as("check iocCategoryName").isEqualTo(actual.getIocCategoryName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIocCategoryUpdatableRelationshipsEquals(IocCategory expected, IocCategory actual) {
        // empty method
    }
}
