package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrivacyTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivacyTypeAllPropertiesEquals(PrivacyType expected, PrivacyType actual) {
        assertPrivacyTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertPrivacyTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivacyTypeAllUpdatablePropertiesEquals(PrivacyType expected, PrivacyType actual) {
        assertPrivacyTypeUpdatableFieldsEquals(expected, actual);
        assertPrivacyTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivacyTypeAutoGeneratedPropertiesEquals(PrivacyType expected, PrivacyType actual) {
        assertThat(expected)
            .as("Verify PrivacyType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivacyTypeUpdatableFieldsEquals(PrivacyType expected, PrivacyType actual) {
        assertThat(expected)
            .as("Verify PrivacyType relevant properties")
            .satisfies(e -> assertThat(e.getPrivacyTypeId()).as("check privacyTypeId").isEqualTo(actual.getPrivacyTypeId()))
            .satisfies(e -> assertThat(e.getPrivacyTypeName()).as("check privacyTypeName").isEqualTo(actual.getPrivacyTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivacyTypeUpdatableRelationshipsEquals(PrivacyType expected, PrivacyType actual) {
        // empty method
    }
}
