package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductsToUpdateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductsToUpdateAllPropertiesEquals(ProductsToUpdate expected, ProductsToUpdate actual) {
        assertProductsToUpdateAutoGeneratedPropertiesEquals(expected, actual);
        assertProductsToUpdateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductsToUpdateAllUpdatablePropertiesEquals(ProductsToUpdate expected, ProductsToUpdate actual) {
        assertProductsToUpdateUpdatableFieldsEquals(expected, actual);
        assertProductsToUpdateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductsToUpdateAutoGeneratedPropertiesEquals(ProductsToUpdate expected, ProductsToUpdate actual) {
        assertThat(expected)
            .as("Verify ProductsToUpdate auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductsToUpdateUpdatableFieldsEquals(ProductsToUpdate expected, ProductsToUpdate actual) {
        assertThat(expected)
            .as("Verify ProductsToUpdate relevant properties")
            .satisfies(e -> assertThat(e.getMaxGLNCode()).as("check maxGLNCode").isEqualTo(actual.getMaxGLNCode()))
            .satisfies(e -> assertThat(e.getMaxManufacturerID()).as("check maxManufacturerID").isEqualTo(actual.getMaxManufacturerID()))
            .satisfies(e -> assertThat(e.getProductId()).as("check productId").isEqualTo(actual.getProductId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductsToUpdateUpdatableRelationshipsEquals(ProductsToUpdate expected, ProductsToUpdate actual) {
        // empty method
    }
}
