package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductUpcAllocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductUpcAllocationAllPropertiesEquals(ProductUpcAllocation expected, ProductUpcAllocation actual) {
        assertProductUpcAllocationAutoGeneratedPropertiesEquals(expected, actual);
        assertProductUpcAllocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductUpcAllocationAllUpdatablePropertiesEquals(ProductUpcAllocation expected, ProductUpcAllocation actual) {
        assertProductUpcAllocationUpdatableFieldsEquals(expected, actual);
        assertProductUpcAllocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductUpcAllocationAutoGeneratedPropertiesEquals(ProductUpcAllocation expected, ProductUpcAllocation actual) {
        assertThat(expected)
            .as("Verify ProductUpcAllocation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductUpcAllocationUpdatableFieldsEquals(ProductUpcAllocation expected, ProductUpcAllocation actual) {
        assertThat(expected)
            .as("Verify ProductUpcAllocation relevant properties")
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedOn()).as("check createdOn").isEqualTo(actual.getCreatedOn()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()))
            .satisfies(e -> assertThat(e.getProductId()).as("check productId").isEqualTo(actual.getProductId()))
            .satisfies(e -> assertThat(e.getProductUpcId()).as("check productUpcId").isEqualTo(actual.getProductUpcId()))
            .satisfies(e -> assertThat(e.getuPC()).as("check uPC").isEqualTo(actual.getuPC()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedOn()).as("check updatedOn").isEqualTo(actual.getUpdatedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductUpcAllocationUpdatableRelationshipsEquals(ProductUpcAllocation expected, ProductUpcAllocation actual) {
        // empty method
    }
}
