package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductDistrictAllocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductDistrictAllocationAllPropertiesEquals(
        ProductDistrictAllocation expected,
        ProductDistrictAllocation actual
    ) {
        assertProductDistrictAllocationAutoGeneratedPropertiesEquals(expected, actual);
        assertProductDistrictAllocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductDistrictAllocationAllUpdatablePropertiesEquals(
        ProductDistrictAllocation expected,
        ProductDistrictAllocation actual
    ) {
        assertProductDistrictAllocationUpdatableFieldsEquals(expected, actual);
        assertProductDistrictAllocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductDistrictAllocationAutoGeneratedPropertiesEquals(
        ProductDistrictAllocation expected,
        ProductDistrictAllocation actual
    ) {
        assertThat(expected)
            .as("Verify ProductDistrictAllocation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductDistrictAllocationUpdatableFieldsEquals(
        ProductDistrictAllocation expected,
        ProductDistrictAllocation actual
    ) {
        assertThat(expected)
            .as("Verify ProductDistrictAllocation relevant properties")
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedOn()).as("check createdOn").isEqualTo(actual.getCreatedOn()))
            .satisfies(e -> assertThat(e.getIsAllocated()).as("check isAllocated").isEqualTo(actual.getIsAllocated()))
            .satisfies(e ->
                assertThat(e.getProductDistrictAllocationId())
                    .as("check productDistrictAllocationId")
                    .isEqualTo(actual.getProductDistrictAllocationId())
            )
            .satisfies(e -> assertThat(e.getProductId()).as("check productId").isEqualTo(actual.getProductId()))
            .satisfies(e -> assertThat(e.getSchoolDistrictId()).as("check schoolDistrictId").isEqualTo(actual.getSchoolDistrictId()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedOn()).as("check updatedOn").isEqualTo(actual.getUpdatedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductDistrictAllocationUpdatableRelationshipsEquals(
        ProductDistrictAllocation expected,
        ProductDistrictAllocation actual
    ) {
        // empty method
    }
}
