package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductH7OldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductH7OldAllPropertiesEquals(ProductH7Old expected, ProductH7Old actual) {
        assertProductH7OldAutoGeneratedPropertiesEquals(expected, actual);
        assertProductH7OldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductH7OldAllUpdatablePropertiesEquals(ProductH7Old expected, ProductH7Old actual) {
        assertProductH7OldUpdatableFieldsEquals(expected, actual);
        assertProductH7OldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductH7OldAutoGeneratedPropertiesEquals(ProductH7Old expected, ProductH7Old actual) {
        assertThat(expected)
            .as("Verify ProductH7Old auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductH7OldUpdatableFieldsEquals(ProductH7Old expected, ProductH7Old actual) {
        assertThat(expected)
            .as("Verify ProductH7Old relevant properties")
            .satisfies(e -> assertThat(e.getGtinUpc()).as("check gtinUpc").isEqualTo(actual.getGtinUpc()))
            .satisfies(e -> assertThat(e.geth7KeywordId()).as("check h7KeywordId").isEqualTo(actual.geth7KeywordId()))
            .satisfies(e -> assertThat(e.getiOCGroup()).as("check iOCGroup").isEqualTo(actual.getiOCGroup()))
            .satisfies(e -> assertThat(e.getProductH7Id()).as("check productH7Id").isEqualTo(actual.getProductH7Id()))
            .satisfies(e -> assertThat(e.getProductId()).as("check productId").isEqualTo(actual.getProductId()))
            .satisfies(e -> assertThat(e.getProductName()).as("check productName").isEqualTo(actual.getProductName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductH7OldUpdatableRelationshipsEquals(ProductH7Old expected, ProductH7Old actual) {
        // empty method
    }
}
