package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductManufacturerAllocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductManufacturerAllocationAllPropertiesEquals(
        ProductManufacturerAllocation expected,
        ProductManufacturerAllocation actual
    ) {
        assertProductManufacturerAllocationAutoGeneratedPropertiesEquals(expected, actual);
        assertProductManufacturerAllocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductManufacturerAllocationAllUpdatablePropertiesEquals(
        ProductManufacturerAllocation expected,
        ProductManufacturerAllocation actual
    ) {
        assertProductManufacturerAllocationUpdatableFieldsEquals(expected, actual);
        assertProductManufacturerAllocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductManufacturerAllocationAutoGeneratedPropertiesEquals(
        ProductManufacturerAllocation expected,
        ProductManufacturerAllocation actual
    ) {
        assertThat(expected)
            .as("Verify ProductManufacturerAllocation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductManufacturerAllocationUpdatableFieldsEquals(
        ProductManufacturerAllocation expected,
        ProductManufacturerAllocation actual
    ) {
        assertThat(expected)
            .as("Verify ProductManufacturerAllocation relevant properties")
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedOn()).as("check createdOn").isEqualTo(actual.getCreatedOn()))
            .satisfies(e -> assertThat(e.getIsAllocated()).as("check isAllocated").isEqualTo(actual.getIsAllocated()))
            .satisfies(e -> assertThat(e.getManufactureId()).as("check manufactureId").isEqualTo(actual.getManufactureId()))
            .satisfies(e -> assertThat(e.getProductId()).as("check productId").isEqualTo(actual.getProductId()))
            .satisfies(e ->
                assertThat(e.getProductManufacturerAllocationId())
                    .as("check productManufacturerAllocationId")
                    .isEqualTo(actual.getProductManufacturerAllocationId())
            )
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedOn()).as("check updatedOn").isEqualTo(actual.getUpdatedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductManufacturerAllocationUpdatableRelationshipsEquals(
        ProductManufacturerAllocation expected,
        ProductManufacturerAllocation actual
    ) {
        // empty method
    }
}
