package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StorageTypesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageTypesAllPropertiesEquals(StorageTypes expected, StorageTypes actual) {
        assertStorageTypesAutoGeneratedPropertiesEquals(expected, actual);
        assertStorageTypesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageTypesAllUpdatablePropertiesEquals(StorageTypes expected, StorageTypes actual) {
        assertStorageTypesUpdatableFieldsEquals(expected, actual);
        assertStorageTypesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageTypesAutoGeneratedPropertiesEquals(StorageTypes expected, StorageTypes actual) {
        assertThat(expected)
            .as("Verify StorageTypes auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageTypesUpdatableFieldsEquals(StorageTypes expected, StorageTypes actual) {
        assertThat(expected)
            .as("Verify StorageTypes relevant properties")
            .satisfies(e -> assertThat(e.getStorageTypeId()).as("check storageTypeId").isEqualTo(actual.getStorageTypeId()))
            .satisfies(e -> assertThat(e.getStorageTypeName()).as("check storageTypeName").isEqualTo(actual.getStorageTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageTypesUpdatableRelationshipsEquals(StorageTypes expected, StorageTypes actual) {
        // empty method
    }
}
