package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SupportCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportCategoryAllPropertiesEquals(SupportCategory expected, SupportCategory actual) {
        assertSupportCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertSupportCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportCategoryAllUpdatablePropertiesEquals(SupportCategory expected, SupportCategory actual) {
        assertSupportCategoryUpdatableFieldsEquals(expected, actual);
        assertSupportCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportCategoryAutoGeneratedPropertiesEquals(SupportCategory expected, SupportCategory actual) {
        assertThat(expected)
            .as("Verify SupportCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportCategoryUpdatableFieldsEquals(SupportCategory expected, SupportCategory actual) {
        assertThat(expected)
            .as("Verify SupportCategory relevant properties")
            .satisfies(e -> assertThat(e.getSupportCategoryId()).as("check supportCategoryId").isEqualTo(actual.getSupportCategoryId()))
            .satisfies(e ->
                assertThat(e.getSupportCategoryName()).as("check supportCategoryName").isEqualTo(actual.getSupportCategoryName())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportCategoryUpdatableRelationshipsEquals(SupportCategory expected, SupportCategory actual) {
        // empty method
    }
}
